name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Format
      run: gofmt -w=true .
      
    - name: Save auto-formatting
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic gofmt fixes
        
    - name: Build
      run: make

    - name: Run tests
      run: go test -v -race ./...